//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Pencils
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Pencil.
    /// </summary>
    //  *** Start programmer edit section *** (Pencil CustomAttributes)

    //  *** End programmer edit section *** (Pencil CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PencilE", new string[] {
            "Name as \'Name\'"})]
    [View("PencilL", new string[] {
            "Name as \'Name\'"})]
    public class Pencil : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (Pencil CustomMembers)

        //  *** End programmer edit section *** (Pencil CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Pencil.Name CustomAttributes)

        //  *** End programmer edit section *** (Pencil.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Pencil.Name Get start)

                //  *** End programmer edit section *** (Pencil.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Pencil.Name Get end)

                //  *** End programmer edit section *** (Pencil.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Pencil.Name Set start)

                //  *** End programmer edit section *** (Pencil.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Pencil.Name Set end)

                //  *** End programmer edit section *** (Pencil.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PencilE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PencilE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PencilE", typeof(IIS.Pencils.Pencil));
                }
            }
            
            /// <summary>
            /// "PencilL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PencilL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PencilL", typeof(IIS.Pencils.Pencil));
                }
            }
        }
    }
}
